### ISSUE TITLE
Gestion des abonnements

### ISSUE THREAD

**Issue by max21** [PayboxByVerifone/Magento-2.0.x-2.2.x#25]
Bonjour,
A priori la gestion des abonnements n'a pas été développée dans ce module.
D'après la documentation technique d'intégration de Paybox, il faut envoyer un certain nombre de paramètres pour la création d'un abonnement : 

PBX_2MONT
PBX_NBPAIE
PBX_FREQ
PBX_QUAND
PBX_DELAIS

Existe-t-il une implémentation de ce mode de paiement ?

--

Hello,
It seems that the management of subscriptions has not been developed in this module.
According to the Paybox integration technical documentation, a certain number of parameters must be sent for the creation of a subscription:

PBX_2MONT
PBX_NBPAIE
PBX_FREQ
PBX_QUAND
PBX_DELAIS

Is there an implementation of this payment method?

**Comment by jcpaybox** [comment]
Hi, sorry for this late reply.

Indeed we have not implemented the recurring payments / subscription integration. 
This extension is a free plugin that is intended to serve the most commonly used features of our e-commerce platform.

Some developpers have made a more feature-rich integration, see sellxed for instance.

Regards.
Paybox
